### ISSUE TITLE
Career Support - Resumes - Build your resume

### ISSUE THREAD

**Issue by KGMAC3** [KGMAC3/assignments#30]
# Key areas of Information to include:

## Contact information
- [ ] Email
- [ ] Phone Number (Google numbers are great if you want to protect your personal number)
- [ ] Github link
- [ ] Portfolio link

## Summary
- [ ] Should be a brief paragraph (three to five sentences) that shows the value you bring by highlighting your skills and a couple of big career wins. But rather than labeling it a “summary,” use a headline that encapsulates your credentials.

## Skills
- [ ] You’ll want to incorporate the right keywords, optimize your resume for applicant tracking systems

## Professional experience
- [ ] Focus on your accomplishments rather than your day-to-day responsibilities
Education
- [ ] Write where you went college and your degree.
- [ ] It’s ok to move this towards the top if you have limited work experience and want to highlight your experience at SDG

## Bonus:
- [ ] Volunteering and community service

## Due Date: Wednesday, September 25th
 - [ ] Upload or submit a link to your resume for review.

**Comment by KGMAC3** [comment]
[Kyle Macalindong -Resume r6.28.19.pdf](https://github.com/KGMAC3/assignments/files/3648142/Kyle.Macalindong.-Resume.r6.28.19.pdf)

**Comment by KGMAC3** [comment]
[Uploading Kyle Macalindong -Resume v2.pdf…]()

**Comment by KGMAC3** [comment]
[Kyle Macalindong -Resume v3.pdf](https://github.com/KGMAC3/assignments/files/3658591/Kyle.Macalindong.-Resume.v3.pdf)

had a typo

**Comment by ktrammell95** [comment]
Very nice layout, I would suggest adding a link to your LinkedIn and GitHub in the top contact area.

Once you work on some more assignments and get them graded you might want to think about which ones you liked the most or are the proudest of and highlight them on your resume to show off your development skills
